openapi: 3.0.0
info:
  title: XLanguage API
  description: API documentation for XLanguage multilingual chat application
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Development server

paths:
  /chat:
    post:
      summary: Send a chat message
      description: Send a message and receive a translated response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: User's message
                target_language:
                  type: string
                  description: Target language for translation
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: Translated response
                  original_language:
                    type: string
                    description: Detected source language
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /user/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
